version: '3.4'

services:
  clubmanager:
    image: ${DOCKER_REGISTRY-}clubmanager
    build:
      context: .
      dockerfile: ClubManager/Dockerfile
    ports:
       - 8080:8080
       - 8081:8081     

volumes:
    sqlserverdata:

