version: '3.4'

services:
  clubmanager:
    image: ${DOCKER_REGISTRY-}clubmanager
    container_name: clubManager-api
    build:
      context: .
      dockerfile: ClubManager/Dockerfile

  clubmanager1:
    image: ${DOCKER_REGISTRY-}clubmanager
    container_name: clubManager-api1
    build:
      context: .
      dockerfile: ClubManager/Dockerfile  
   
  clubmanager2:
    image: ${DOCKER_REGISTRY-}clubmanager
    container_name: clubManager-api2
    build:
      context: .
      dockerfile: ClubManager/Dockerfile

volumes:
    sqlserverdata:

